---
type: config
log_level: info
cpu_affinity: [0]

status_monitor:
  kotekan_stage: bufferStatus
  print_status: false
  time_delay: 1000000

updatable_config:
  flagging:
    kotekan_update_endpoint: "json"
    start_time: 1535048997.
    update_id: "initial_flags"
    bad_inputs: [  46,   84,  107,  136 ]
  gains:
    kotekan_update_endpoint: "json"
    start_time: 1575950518.4
    update_id: "zero_gain"
    transition_interval: 300.0
    new_state: true
  26m_gated:
    kotekan_update_endpoint: "json"
    enabled: false